name: build multiarch DOCKER Image

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    
      - name: build the image based on branch
        run: |
          docker buildx build --push \
            --tag pnatel/photo_folder_manager:${GITHUB_REF##*/} \
            --build-arg BUILD_TAG=${GITHUB_REF##*/}
            --file ./docker/Dockerfile \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .      
      - name: build a latest image
        if: endsWith(github.ref, '/master')
        run: |
          docker buildx build --push \
            --tag pnatel/photo_folder_manager:latest \
            --file ./docker/Dockerfile \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
